export const translations = {
  appName: "Tu casa inteligente",
  appSubtitle: "Panel de Control",
  menuInicio: "Inicio",
  menuDispositivos: "Dispositivos",
  menuSeguimiento: "Seguimiento",
  menuChat: "Chat",
  welcome: "Bienvenido",
  enterDeviceCode: "Ingresa el código de tu dispositivo para agregarlo.",
  deviceCodeLabel: "Código de dispositivo",
  deviceCodePlaceholder: "Ej: SH-2024-XXXX",
  deviceDescriptionLabel: "Descripción (opcional)",
  deviceDescriptionPlaceholder: "Ej: Termostato sala",
  selectHouseLabel: "Seleccionar casa",
  newHouseButton: "Casa",
  addDeviceButton: "Agregar dispositivo",
  myDevices: "Mis Dispositivos",
  noDevices: "No tienes dispositivos agregados aún.",
  houseLabel: "Casa",
  addedLabel: "Agregado",
  editDevice: "Editar Dispositivo",
  deviceCodeEditLabel: "Código del dispositivo",
  deleteConfirmTitle: "Confirmar eliminación",
  deleteConfirmMessage:
    '¿Estás seguro de que deseas eliminar el dispositivo "{device}"?',
  cancel: "Cancelar",
  delete: "Eliminar",
  save: "Guardar",
  add: "Agregar",
  settings: "Configuración",
  nameLabel: "Nombre",
  emailLabel: "Email",
  close: "Cerrar",
  newHouseDialogTitle: "Nueva Casa",
  houseNameLabel: "Nombre de la casa",
  houseDescriptionLabel: "Descripción (opcional)",
  trackingTitle: "Seguimiento de Actividad",
  trackingDescription:
    "Aquí podrás ver el historial de eventos de tus dispositivos.",
  trackingPlaceholder: "Gráficos y métricas próximamente.",
  snackbarDeviceAdded: "Dispositivo agregado correctamente",
  snackbarDeviceUpdated: "Dispositivo actualizado",
  snackbarDeviceDeleted: "Dispositivo eliminado",
  snackbarHouseAdded: 'Casa "{name}" agregada',
  snackbarSettingsSaved: "Configuración guardada",
  snackbarErrorDeviceCode: "Por favor ingresa un código de dispositivo",
  snackbarErrorSelectHouse: "Selecciona una casa",
  snackbarErrorHouseName: "Ingresa un nombre para la casa",
  snackbarErrorEmptyCode: "El código no puede estar vacío",
  houseMain: "Casa Principal",
  houseMainDesc: "Residencia principal",
  houseOffice: "Oficina",
  houseOfficeDesc: "Oficina central",
  houseCountry: "Casa de Campo",
  houseCountryDesc: "Casa de vacaciones",
  chatTitle: "Asistente Inteligente",
  chatSubtitle: "Haz preguntas sobre tus dispositivos o controla tu hogar",
  chatPlaceholder: "Escribe tu pregunta...",
  chatSendButton: "Enviar",
  chatRecordButton: "Grabar mensaje",
  chatStopRecordButton: "Detener grabación",
  chatEmptyState:
    "Inicia una conversación. Puedes preguntar sobre tus dispositivos, hacer órdenes de control, o simplemente conversar.",
  chatErrorTranscribe: "No se pudo transcribir el audio",
};
